name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.operating_system }}
    strategy:
      matrix:
        operating_system: [ ubuntu-latest, macos-latest ]
        ruby_version: [ 2.6, 2.7 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
